export const API_PATH  = {
  V1: '/v1',
  PRODUCT: '/product',
  PROJECT: '/project',
  DESIGN: '/design',
  LAYOUT: '/layout',
  BACKGROUND: '/background',
  TEMPLATE: '/template',
  RESOURCE: '/resource',
  SEARCH_TAG: '/searchTag',
  EXISTENCE: '/existence',
  MULTIFORM: '/multiform',
  RESAVE: '/resave',
  SEARCH: '/search',
  JSON: '/json',
  URL: '/url',
  ALL: '/all',
  MY: '/my',
  LOGO: '/logo',
  FILE: '/file',
  ITEM: '/item',
  OPTION: '/option',
  CODE: '/code',
  EDITOR: '/editor',
  SKIN: '/skin',
  COUNT: '/count',
  PHONE_CASE: '/phoneCase',
  CASE_OPTION: '/caseOption',
  DEVICE_INFO: '/deviceInfo',
  PRODUCT_SALE_OPTION_INFO: '/productSaleOptionInfo',
  HOLIDAY: '/holiday',
  COMMON: '/common',

  USER_LOGIN: '/account/user/login',
  RESOURCE_ALL: '/resource/all',
  RESOURCE_MY: '/resource/my',

  RESOURCE_SKIN_DEVICE: "/Upload/Data1/Resource/skin/device/",
  RESOURCE_SKIN_EDITOR: "/Upload/Data1/Resource/skin/editor/",
  RESOURCE_SKIN_LIST: "/Upload/Data1/Resource/skin/designList2/",
  RESOURCE_SKIN_DETAIL: "/Upload/Data1/Resource/skin/detail2/",
  RESOURCE_SKIN_EDITOR_TOP: "/Upload/Data1/Resource/skin/editorTop/",
  RESOURCE_SKIN_LIST_TOP: "/Upload/Data1/Resource/skin/designListTop/",
  RESOURCE_SKIN_DETAIL_TOP: "/Upload/Data1/Resource/skin/detailTop/",
  RESOURCE_SCENE_MASK: "/Upload/Data1/Resource/skin/sceneMaskEditor/",

  COUNTRY_CODE: '?countryCode=',


  ARTWORK_RESOURCE_SKIN: 'artwork-editor/resource/product/'
}
