version: 0.0
os: linux
files:
  - source: /oround-nextjs-image-generator
    destination: /home/ec2-user/oround-nextjs-image-generator/oround-nextjs-image-generator
permissions:
  - object: /home/ec2-user/oround-nextjs-image-generator/oround-nextjs-image-generator
    owner: ec2-user
    group: ec2-user
    mode: 755
