version: 0.0
os: linux
files:
  - source: /
    destination: /snaps/servers/oround-image-generator
permissions:
  - object: /snaps/servers/oround-image-generator
    owner: snapsadmin
    group: snapsadmin
    mode: 755
hooks:
  ApplicationStop:
    - location: bin/stop.sh
      timeout: 30
      runas: snapsadmin
  BeforeInstall:
    - location: bin/before-install.sh
      timeout: 30
      runas: snapsadmin
  ApplicationStart:
    - location: bin/start.sh
      timeout: 30
      runas: snapsadmin
